//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03Model.Models
{
    using System;//using在namespace裡面外面都可以
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    
    public partial class tStudent
    {
        [DisplayName("學號")]
        [Required(ErrorMessage ="學號必甜喔")]
        [RegularExpression("[12][0-5][6-9][0-9]{3}",ErrorMessage = "學號格式錯誤120569093")]
        //[0-9]{3}0-9打3碼 {3,}3次以上 {,3}最多3次{3,10}最多共10碼
        public string fStuId { get; set; }

        [DisplayName("姓名")]
        [Required(ErrorMessage = "姓名必填喔")]
        [StringLength(100)]
        public string fName { get; set; }

        [DisplayName("信箱")]
        [Required(ErrorMessage = "信箱必填喔")]
        [EmailAddress(ErrorMessage ="信箱格式錯誤")]
        public string fEmail { get; set; }
        [DisplayName("成績")]
        [Required(ErrorMessage = "成績必填喔")]
        [Range(0,100,ErrorMessage ="成績要0-100包含")]
        //輸入範圍在0-100
        public Nullable<int> fScore { get; set; }//允許為Null
    }
}
